//! The stabiliser chain of #21, checked against a definition rather than
//! against another implementation.
//!
//! # What the reference is
//!
//! For a group small enough to write out, the answer can be computed from first
//! principles: close the generators under composition until nothing new
//! appears, and the result is the group. Its size is the order, and membership
//! is a lookup. [`closure`] below is that computation, and it is deliberately
//! naive, because a reference that shares an optimisation with the thing it
//! checks shares the mistake in it.
//!
//! This is not the oracle of #23. That issue asks for one covering orbits and
//! stabilisers as well, with property tests over random generator sets and a
//! stated boundary where enumeration stops being usable. What is here is the
//! part #21's own conditions name: a brute-force order and an exhaustive
//! membership answer, for the cases below.
//!
//! # Where the random generator sets come from
//!
//! From the generator at the bottom of this file, for the reason
//! `tests/permutation.rs` gives for its own: this workspace has no third-party
//! dependency, and every entry added to one is a supply chain entry the policy
//! of #38 has to account for. The two sources are separate because an
//! integration test file is its own crate and sharing one would mean a module
//! both files reach into, and because what is drawn here is a set of generators
//! rather than a single permutation.

use indexwerk_core::permutation::{Permutation, PermutationError};
use indexwerk_core::stabiliser_chain::{ChainCache, StabiliserChain};

/// The widest group this file enumerates by brute force.
///
/// Six points is 720 permutations, which is what the exhaustive membership test
/// walks per case, and the whole file runs well inside the time budget of a
/// suite that runs on every change. Seven would be 5040 and eight 40320, and
/// the cost is in the closure rather than in the walk: the closure composes
/// every element with every generator until it stops growing. Where the
/// boundary is exactly, and what is done above it, is #23.
const ENUMERABLE_WIDTH: usize = 6;

/// A named case, its generators, and the order it is known to have.
struct Case {
    name: &'static str,
    width: usize,
    generators: Vec<Permutation>,
    known_order: u128,
}

/// The standard cases #21 names, in the order it names them.
///
/// The orders are the definitions of the groups rather than measurements of
/// them. `|S_n| = n!` and `|A_n| = n!/2` and `|C_n| = n` and the order of a
/// direct product is the product of the orders, all in Rotman, *An Introduction
/// to the Theory of Groups*, 4th edition, Springer 1995, chapter 3. The Riemann
/// case is the one that is not a definition and it is the reason this list
/// exists: the slot symmetry generated by the antisymmetry of each pair and the
/// exchange of the two pairs is the wreath product of two groups of order two,
/// which has order eight, and the first Bianchi identity is not in it because it
/// is a multi-term identity and not a slot symmetry at all
/// (`docs/adr/0003-single-term-only.md`).
fn standard_cases() -> Vec<Case> {
    let mut cases = Vec::new();

    for width in 1..=ENUMERABLE_WIDTH {
        cases.push(Case {
            name: "symmetric group",
            width,
            generators: symmetric_generators(width),
            known_order: factorial(width),
        });
    }

    for width in 3..=ENUMERABLE_WIDTH {
        cases.push(Case {
            name: "alternating group",
            width,
            generators: alternating_generators(width),
            known_order: factorial(width) / 2,
        });
    }

    for width in 1..=ENUMERABLE_WIDTH {
        cases.push(Case {
            name: "cyclic group",
            width,
            generators: vec![cycle(width, &(0..width).collect::<Vec<usize>>())],
            known_order: width as u128,
        });
    }

    for left in 1..=3 {
        for right in 1..=3 {
            let mut generators = symmetric_generators(left);
            for generator in symmetric_generators(right) {
                generators.push(shift(&generator, left, left + right));
            }
            let generators = generators
                .iter()
                .map(|generator| widen(generator, left + right))
                .collect();
            cases.push(Case {
                name: "direct product of two symmetric groups",
                width: left + right,
                generators,
                known_order: factorial(left) * factorial(right),
            });
        }
    }

    cases.push(Case {
        name: "Riemann slot symmetry",
        width: 4,
        generators: riemann_generators(),
        known_order: 8,
    });

    cases.push(Case {
        name: "trivial group, given no generators",
        width: 4,
        generators: Vec::new(),
        known_order: 1,
    });

    cases.push(Case {
        name: "trivial group, given only the identity",
        width: 4,
        generators: vec![Permutation::identity(4)],
        known_order: 1,
    });

    cases
}

#[test]
fn the_order_from_the_chain_is_the_order_of_the_enumerated_group() {
    for case in standard_cases() {
        let chain = StabiliserChain::new(case.width, case.generators.clone())
            .expect("the generators are on the case width");
        let enumerated = closure(case.width, &case.generators);

        assert_eq!(
            chain.order(),
            Some(enumerated.len() as u128),
            "{} on {} points: the chain and the enumeration disagree",
            case.name,
            case.width
        );
    }
}

#[test]
fn the_order_from_the_chain_is_the_order_the_case_is_known_to_have() {
    for case in standard_cases() {
        let chain = StabiliserChain::new(case.width, case.generators.clone())
            .expect("the generators are on the case width");

        assert_eq!(
            chain.order(),
            Some(case.known_order),
            "{} on {} points: the chain disagrees with the stated order",
            case.name,
            case.width
        );
    }
}

#[test]
fn the_order_from_the_chain_is_the_order_of_a_randomly_generated_group() {
    let mut source = Source::new();
    for _ in 0..CASES {
        let width = 2 + source.below(ENUMERABLE_WIDTH - 1);
        let generators = source.generator_set(width);

        let chain = StabiliserChain::new(width, generators.clone())
            .expect("the generators are on the drawn width");
        let enumerated = closure(width, &generators);

        assert_eq!(
            chain.order(),
            Some(enumerated.len() as u128),
            "the chain and the enumeration disagree on {}",
            render_generators(&generators)
        );
    }
}

#[test]
fn membership_is_answered_correctly_for_every_permutation_of_the_width() {
    for case in standard_cases() {
        if case.width > ENUMERABLE_WIDTH {
            continue;
        }
        let chain = StabiliserChain::new(case.width, case.generators.clone())
            .expect("the generators are on the case width");
        let enumerated = closure(case.width, &case.generators);

        // Every permutation of the width, not a sample of them, so the answer
        // is checked on the non-elements as well. A membership test that
        // answered yes to everything would pass a test that only fed it
        // elements, and that is the failure this walk exists to catch.
        for candidate in every_permutation(case.width) {
            let expected = enumerated.contains(&candidate);
            let answered = chain
                .contains(&candidate)
                .expect("the candidate is on the chain width");

            assert_eq!(
                answered,
                expected,
                "{} on {} points: membership of {} was answered {}",
                case.name,
                case.width,
                render_generators(std::slice::from_ref(&candidate)),
                answered
            );
        }
    }
}

#[test]
fn membership_is_answered_correctly_for_a_randomly_generated_group() {
    let mut source = Source::new();
    for _ in 0..CASES {
        let width = 2 + source.below(4);
        let generators = source.generator_set(width);

        let chain = StabiliserChain::new(width, generators.clone())
            .expect("the generators are on the drawn width");
        let enumerated = closure(width, &generators);

        for candidate in every_permutation(width) {
            let expected = enumerated.contains(&candidate);
            let answered = chain
                .contains(&candidate)
                .expect("the candidate is on the chain width");
            assert_eq!(
                answered,
                expected,
                "membership disagreed on {} for the group {}",
                render_generators(std::slice::from_ref(&candidate)),
                render_generators(&generators)
            );
        }
    }
}

#[test]
fn every_strong_generator_is_an_element_and_the_chain_is_consistent_with_itself() {
    for case in standard_cases() {
        let chain = StabiliserChain::new(case.width, case.generators.clone())
            .expect("the generators are on the case width");

        for generator in chain.strong_generators() {
            assert!(
                chain
                    .contains(&generator)
                    .expect("a strong generator is on the chain width"),
                "{}: a strong generator is not an element of the group it generates",
                case.name
            );
        }

        // The base is what the chain is a chain of, so a level's generators all
        // fix every base point above that level. This is the property the
        // strip in the membership test relies on, and it is the one that goes
        // wrong when a residue is added to too few levels.
        for (index, level) in chain.levels().iter().enumerate() {
            for higher in chain.base().into_iter().take(index) {
                for generator in level.generators() {
                    assert_eq!(
                        generator.image(higher),
                        Some(higher),
                        "{}: a generator of level {index} moves the base point {higher} above it",
                        case.name
                    );
                }
            }
            assert_eq!(
                level.orbit().first(),
                Some(&level.base()),
                "{}: an orbit does not start at its own base point",
                case.name
            );
        }

        assert_eq!(
            chain.order(),
            product(&chain.basic_orbit_lengths()),
            "{}: the order and the orbit lengths disagree",
            case.name
        );
    }
}

#[test]
fn the_transversal_takes_the_base_point_where_it_says_it_does() {
    for case in standard_cases() {
        let chain = StabiliserChain::new(case.width, case.generators.clone())
            .expect("the generators are on the case width");

        for level in chain.levels() {
            for &point in level.orbit() {
                let element = level
                    .transversal(point)
                    .expect("a point of the orbit has a transversal element");
                assert_eq!(
                    element.image(level.base()),
                    Some(point),
                    "{}: the transversal element for {point} does not reach it",
                    case.name
                );
                assert!(
                    chain
                        .contains(element)
                        .expect("a transversal element is on the chain width"),
                    "{}: a transversal element is not in the group",
                    case.name
                );
            }
            for point in 0..case.width {
                assert_eq!(
                    level.transversal(point).is_some(),
                    level.orbit().contains(&point),
                    "{}: the transversal and the orbit disagree about {point}",
                    case.name
                );
            }
        }
    }
}

#[test]
fn the_same_generators_in_the_same_order_produce_a_byte_identical_chain() {
    for case in standard_cases() {
        let first = StabiliserChain::new(case.width, case.generators.clone())
            .expect("the generators are on the case width");
        let second = StabiliserChain::new(case.width, case.generators.clone())
            .expect("the generators are on the case width");

        assert_eq!(
            first.render().as_bytes(),
            second.render().as_bytes(),
            "{} on {} points: two builds from one input rendered differently",
            case.name,
            case.width
        );
        assert_eq!(first, second);
    }
}

#[test]
fn a_rendered_chain_carries_every_level_and_names_the_width() {
    let chain = StabiliserChain::new(4, riemann_generators()).expect("width 4 generators");
    let rendered = chain.render();

    assert!(
        rendered.starts_with("width 4\n"),
        "the render does not open with the width: {rendered}"
    );
    assert_eq!(
        rendered.matches("level ").count(),
        chain.levels().len(),
        "the render does not carry one line per level: {rendered}"
    );
    assert!(
        rendered.ends_with('\n'),
        "the render does not end with a newline: {rendered}"
    );
}

#[test]
fn a_second_request_for_one_symmetry_does_not_build_a_second_chain() {
    let symmetry = riemann_generators();
    let mut cache = ChainCache::new();
    assert!(cache.is_empty());

    let first = cache
        .chain(4, &symmetry)
        .expect("width 4 generators")
        .clone();
    assert_eq!(cache.computations(), 1);
    assert_eq!(cache.len(), 1);

    for _ in 0..8 {
        let again = cache.chain(4, &symmetry).expect("width 4 generators");
        assert_eq!(again.render(), first.render());
    }

    assert_eq!(
        cache.computations(),
        1,
        "the cache built a chain for a symmetry it already held"
    );
    assert_eq!(cache.len(), 1);
}

#[test]
fn a_different_symmetry_is_a_different_entry() {
    let mut cache = ChainCache::new();
    let riemann = riemann_generators();

    cache.chain(4, &riemann).expect("width 4 generators");

    // The near miss is the point of this test. Two generator sets that differ
    // by one generator, and two that differ only in the order the same
    // generators are given in, are three different keys, because the chain is a
    // function of the order as well as of the set.
    let one_fewer: Vec<Permutation> = riemann.iter().skip(1).cloned().collect();
    let reordered: Vec<Permutation> = riemann.iter().rev().cloned().collect();
    let wider = symmetric_generators(5);

    cache.chain(4, &one_fewer).expect("width 4 generators");
    cache.chain(4, &reordered).expect("width 4 generators");
    cache.chain(5, &wider).expect("width 5 generators");

    assert_eq!(cache.computations(), 4);
    assert_eq!(cache.len(), 4);

    // Two chains that describe the same group from different generator orders
    // agree about the group and are not required to be the same chain.
    let by_order = cache
        .chain(4, &riemann)
        .expect("width 4 generators")
        .order();
    let by_reordered = cache
        .chain(4, &reordered)
        .expect("width 4 generators")
        .order();
    assert_eq!(by_order, by_reordered);
    assert_eq!(cache.computations(), 4);
}

#[test]
fn a_refused_symmetry_is_not_stored_and_is_refused_again() {
    let mut cache = ChainCache::new();
    let mismatched = vec![Permutation::new(vec![1, 0, 2]).expect("a permutation of three points")];

    for _ in 0..3 {
        let refused = cache.chain(4, &mismatched);
        assert_eq!(
            refused.err(),
            Some(PermutationError::WidthMismatch { left: 4, right: 3 })
        );
    }

    assert!(cache.is_empty());
    assert_eq!(cache.computations(), 0);
}

#[test]
fn a_generator_of_another_width_is_refused_rather_than_padded() {
    let refused = StabiliserChain::new(
        4,
        vec![
            Permutation::new(vec![1, 0, 2, 3]).expect("a permutation of four points"),
            Permutation::new(vec![1, 0, 2]).expect("a permutation of three points"),
        ],
    );

    assert_eq!(
        refused.err(),
        Some(PermutationError::WidthMismatch { left: 4, right: 3 })
    );

    // The narrow identity is the case that decides whether the refusal is the
    // constructor's or an accident of where the first composition happens. Every
    // other mismatched generator reaches a composition and is refused by
    // `Permutation::then` whether or not anything looked at the widths first.
    // This one is skipped as an identity before it reaches one, so a
    // constructor that did not compare widths would accept it and answer a
    // question about a group on four points from a generator on three.
    let narrow_identity = StabiliserChain::new(4, vec![Permutation::identity(3)]);

    assert_eq!(
        narrow_identity.err(),
        Some(PermutationError::WidthMismatch { left: 4, right: 3 })
    );
}

#[test]
fn a_candidate_of_another_width_is_refused_rather_than_answered() {
    let chain = StabiliserChain::new(4, riemann_generators()).expect("width 4 generators");
    let narrow = Permutation::new(vec![1, 0, 2]).expect("a permutation of three points");

    assert_eq!(
        chain.contains(&narrow).err(),
        Some(PermutationError::WidthMismatch { left: 4, right: 3 })
    );

    // The trivial group is where the comparison is the only thing standing
    // between the caller and an answer. There is no level to strip through, so
    // nothing composes, and a membership test that did not look at the width
    // would compare a permutation of three points against the identity on four
    // and report the mismatch as a mathematical no.
    let trivial = StabiliserChain::new(4, Vec::new()).expect("the trivial group on four points");

    assert_eq!(
        trivial.contains(&narrow).err(),
        Some(PermutationError::WidthMismatch { left: 4, right: 3 })
    );
}

#[test]
fn an_order_that_does_not_fit_is_refused_and_the_orbit_lengths_are_not() {
    // The symmetric group on 35 points. 34! is inside a u128 and 35! is not, so
    // this is the first symmetric group whose order the product cannot carry,
    // and the check is that it says so rather than wrapping.
    let width = 35;
    let chain = StabiliserChain::new(width, symmetric_generators(width))
        .expect("the generators are on this width");

    assert_eq!(chain.order(), None);

    let lengths = chain.basic_orbit_lengths();
    assert_eq!(lengths, (2..=width).rev().collect::<Vec<usize>>());
    assert_eq!(chain.base(), (0..width - 1).collect::<Vec<usize>>());

    // One point fewer is 34!, which fits, and it is the near miss: a check that
    // refused every large group would pass the assertion above for the wrong
    // reason.
    let smaller = StabiliserChain::new(width - 1, symmetric_generators(width - 1))
        .expect("the generators are on this width");
    assert_eq!(smaller.order(), Some(factorial(width - 1)));
}

/// The group, written out, from its generators.
///
/// Breadth first over compositions with the generators until nothing new
/// appears. Nothing here is shared with the chain: it does not know what a base
/// is, it never strips, and it holds the elements in a sorted list so that
/// membership is a comparison of permutations and not of anything the chain
/// computed.
fn closure(width: usize, generators: &[Permutation]) -> Vec<Permutation> {
    let mut elements = vec![Permutation::identity(width)];
    let mut frontier = 0;
    while frontier < elements.len() {
        let element = elements[frontier].clone();
        frontier += 1;
        for generator in generators {
            let product = element
                .then(generator)
                .expect("the generators are on the closure width");
            if !elements.contains(&product) {
                elements.push(product);
            }
        }
    }
    elements.sort();
    elements
}

/// Every permutation of `width` points, in the order of `docs/normal-form.md`.
fn every_permutation(width: usize) -> Vec<Permutation> {
    let mut all = Vec::new();
    let mut images: Vec<usize> = (0..width).collect();
    loop {
        all.push(Permutation::new(images.clone()).expect("a rearrangement of 0..width"));
        if !next_arrangement(&mut images) {
            break;
        }
    }
    all.sort();
    all
}

/// The next arrangement in ascending order, or `false` where there is none.
fn next_arrangement(images: &mut [usize]) -> bool {
    if images.len() < 2 {
        return false;
    }
    let mut pivot = images.len() - 1;
    while pivot > 0 && images[pivot - 1] >= images[pivot] {
        pivot -= 1;
    }
    if pivot == 0 {
        return false;
    }
    let mut swap = images.len() - 1;
    while images[swap] <= images[pivot - 1] {
        swap -= 1;
    }
    images.swap(pivot - 1, swap);
    images[pivot..].reverse();
    true
}

/// The adjacent transpositions, which generate the symmetric group.
fn symmetric_generators(width: usize) -> Vec<Permutation> {
    (1..width)
        .map(|point| transposition(width, point - 1, point))
        .collect()
}

/// The three-cycles through the first two points, which generate the
/// alternating group for a width of at least three.
fn alternating_generators(width: usize) -> Vec<Permutation> {
    (2..width)
        .map(|point| cycle(width, &[0, 1, point]))
        .collect()
}

fn transposition(width: usize, left: usize, right: usize) -> Permutation {
    cycle(width, &[left, right])
}

/// The permutation sending each point of `points` to the next, and the last to
/// the first.
fn cycle(width: usize, points: &[usize]) -> Permutation {
    let mut images: Vec<usize> = (0..width).collect();
    for (position, &point) in points.iter().enumerate() {
        let next = points[(position + 1) % points.len()];
        images[point] = next;
    }
    Permutation::new(images).expect("a cycle over distinct points is a permutation")
}

/// The same permutation acting on the points from `offset` upwards.
fn shift(permutation: &Permutation, offset: usize, width: usize) -> Permutation {
    let mut images: Vec<usize> = (0..width).collect();
    for (point, &image) in permutation.images().iter().enumerate() {
        images[point + offset] = image + offset;
    }
    Permutation::new(images).expect("a shifted permutation of disjoint points")
}

/// The same permutation on more points, fixing the ones it gains.
fn widen(permutation: &Permutation, width: usize) -> Permutation {
    let mut images: Vec<usize> = (0..width).collect();
    for (point, &image) in permutation.images().iter().enumerate() {
        images[point] = image;
    }
    Permutation::new(images).expect("a widened permutation fixes the points it gains")
}

/// The slot symmetry of the Riemann tensor, without the first Bianchi identity.
///
/// Antisymmetric in the first pair, antisymmetric in the second, and symmetric
/// under exchanging the pairs. The signs those symmetries carry are not here:
/// they are a property of the declaration and not of the permutation group, and
/// #25 is where a declaration carries them.
fn riemann_generators() -> Vec<Permutation> {
    vec![
        Permutation::new(vec![1, 0, 2, 3]).expect("a transposition of the first pair"),
        Permutation::new(vec![0, 1, 3, 2]).expect("a transposition of the second pair"),
        Permutation::new(vec![2, 3, 0, 1]).expect("the exchange of the two pairs"),
    ]
}

fn factorial(width: usize) -> u128 {
    (1..=width as u128).product()
}

fn product(lengths: &[usize]) -> Option<u128> {
    let mut total: u128 = 1;
    for &length in lengths {
        total = total.checked_mul(length as u128)?;
    }
    Some(total)
}

fn render_generators(generators: &[Permutation]) -> String {
    generators
        .iter()
        .map(|generator| format!("{:?}", generator.images()))
        .collect::<Vec<String>>()
        .join(", ")
}

/// How many random generator sets each property draws.
const CASES: usize = 60;

/// A deterministic source of small generator sets.
///
/// Xorshift with a multiply, seeded from a constant, in the shape
/// `tests/permutation.rs` uses and for the reason given at the top of this
/// file. The stream is fixed, so a failure reported above is reproduced by
/// running that test again and is the same case on every machine.
struct Source {
    state: u64,
}

impl Source {
    /// The next sixteen hexadecimal digits of the fractional part of pi after
    /// the ones `tests/permutation.rs` seeds from, so the two files draw
    /// different streams rather than the same one twice.
    const SEED: u64 = 0x1319_8A2E_0370_7344;

    fn new() -> Self {
        Source { state: Self::SEED }
    }

    fn next(&mut self) -> u64 {
        let mut state = self.state;
        state ^= state >> 12;
        state ^= state << 25;
        state ^= state >> 27;
        self.state = state;
        state.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    /// A value below `bound`, and zero where the bound is zero.
    fn below(&mut self, bound: usize) -> usize {
        if bound == 0 {
            return 0;
        }
        (self.next() % bound as u64) as usize
    }

    fn permutation(&mut self, width: usize) -> Permutation {
        let mut images: Vec<usize> = (0..width).collect();
        for index in (1..width).rev() {
            let other = self.below(index + 1);
            images.swap(index, other);
        }
        Permutation::new(images).expect("a shuffle of 0..width is a permutation of it")
    }

    /// One to three generators on `width` points.
    ///
    /// A small number on purpose: two generators drawn at random on five points
    /// are the whole symmetric group more often than not, and a set that
    /// generates a proper subgroup is the interesting input for a chain.
    fn generator_set(&mut self, width: usize) -> Vec<Permutation> {
        let count = 1 + self.below(3);
        (0..count).map(|_| self.permutation(width)).collect()
    }
}
